name: Release

on:
  workflow_dispatch:
  push:
    tags:
    - '*.*.*'

env:
  NuGetDirectory: ${{github.workspace}}/nuget

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Create NuGet package
      run: dotnet pack --configuration Release --output ${{env.NuGetDirectory}}
    - uses: actions/upload-artifact@v4
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: |
          ${{env.NuGetDirectory}}/*.nupkg
          ${{env.NuGetDirectory}}/*.snupkg
    - name: Push all NuGet packages
      shell: pwsh
      run: |
        foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include ("*.nupkg", "*.snupkg")))
        {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_TOKEN }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
        }
